#!/usr/bin/env python3
"""Verify standalone canonical bytes and resolved OpenCode reviewer capabilities."""
from __future__ import annotations

import argparse
import hashlib
import json
import math
import os
from pathlib import Path
import stat
import subprocess
from urllib.parse import urlsplit

ALLOWED = {'lean_review_read', 'lean_review_list', 'lean_review_grep'}


class CheckError(RuntimeError):
    pass


def https_endpoint(value: object) -> bool:
    if not isinstance(value, str):
        return False
    try:
        parsed = urlsplit(value)
        parsed.port
    except ValueError:
        return False
    return (parsed.scheme == 'https' and bool(parsed.hostname)
            and parsed.username is None and parsed.password is None
            and '?' not in value and '#' not in value)


def canonical(root: Path, relative: str) -> bytes:
    path = root / relative
    if path.is_symlink() or not path.is_file():
        raise CheckError(f'canonical asset must be a regular file: {relative}')
    result = subprocess.run(['git', 'show', f':{relative}'], cwd=root, capture_output=True)
    if result.returncode or result.stdout != path.read_bytes():
        raise CheckError(f'canonical asset missing or differs from staged Git identity: {relative}')
    return result.stdout


def profile(root: Path, depth: str) -> bytes:
    # Only the execution role changes: no parent, delegation, or inherited project config.
    return canonical(root, f'assets/platforms/opencode/spec-reviewer-{depth}.md').replace(
        b'mode: subagent\n', b'mode: primary\n', 1)


def check(root: Path, runtime: Path, env: dict, config: dict | None = None,
          agent: dict | None = None, depth: str = 'lite', model: str | None = None) -> dict:
    if env.get('OPENCODE_DISABLE_EXTERNAL_SKILLS') != '1':
        raise CheckError('external skill scans must be disabled')
    if Path(env.get('HOME', '/')) != runtime / 'home' or Path(env.get('XDG_CONFIG_HOME', '/')) != runtime / 'config':
        raise CheckError('HOME and XDG config must be isolated')
    for path in (runtime, runtime / 'home', runtime / 'config', runtime / 'config/opencode'):
        if path.is_symlink() or stat.S_IMODE(path.stat().st_mode) != 0o700:
            raise CheckError('isolated runtime directories must have mode 0700')
    directory = runtime / 'config/opencode'
    expected = {
        directory / f'agents/spec-reviewer-{depth}.md': profile(root, depth),
        directory / 'tools/lean_review.ts': canonical(root, 'assets/platforms/opencode/lean_review.ts'),
    }
    # Node package metadata may be generated by OpenCode's own tool loader.
    for path in directory.rglob('*'):
        if 'node_modules' in path.relative_to(directory).parts:
            continue
        if (path.is_file() and path.name not in ('package.json', 'package-lock.json', 'bun.lock', '.gitignore')
                and path not in expected and path != directory / 'opencode.json'):
            raise CheckError(f'noncanonical config provider: {path}')
    for path, data in expected.items():
        if path.is_symlink() or not path.is_file() or path.read_bytes() != data:
            raise CheckError(f'noncanonical runtime bytes: {path}')
    opencode_config = directory / 'opencode.json'
    if opencode_config.is_symlink() or not opencode_config.is_file():
        raise CheckError(f'noncanonical runtime bytes: {opencode_config}')
    try:
        runtime_config = json.loads(opencode_config.read_text())
    except (OSError, ValueError) as exc:
        raise CheckError('OpenCode runtime config is not valid JSON') from exc
    if (not isinstance(runtime_config, dict)
            or set(runtime_config) - {'$schema', 'permission', 'share', 'autoupdate', 'provider'}
            or runtime_config.get('$schema') != 'https://opencode.ai/config.json'
            or runtime_config.get('permission') != {'*': 'deny'}
            or runtime_config.get('share') != 'disabled'
            or runtime_config.get('autoupdate') is not False):
        raise CheckError('noncanonical runtime config keys')
    if model:
        provider, separator, model_id = model.partition('/')
        providers = runtime_config.get('provider', {})
        if not separator or not isinstance(providers, dict) or set(providers) != {provider}:
            raise CheckError('selected OpenCode provider/model definition is missing or noncanonical')
        definition = providers[provider]
        options = definition.get('options') if isinstance(definition, dict) else None
        models = definition.get('models') if isinstance(definition, dict) else None
        if (not isinstance(definition, dict)
                or definition.get('npm') != '@ai-sdk/openai-compatible'
                or not isinstance(options, dict) or set(options) != {'baseURL'}
                or not https_endpoint(options.get('baseURL'))
                or not isinstance(models, dict) or set(models) != {model_id}
                or not isinstance(models[model_id], dict)
                or set(models[model_id]) - {'name', 'reasoning', 'limit', 'variants'}):
            raise CheckError('selected OpenCode provider/model definition is missing or noncanonical')
        model_definition = models[model_id]
        if (('name' in model_definition
             and (not isinstance(model_definition['name'], str) or not model_definition['name']))
                or ('reasoning' in model_definition and not isinstance(model_definition['reasoning'], bool))):
            raise CheckError('selected OpenCode model metadata is malformed')
        limit = model_definition.get('limit')
        if limit is not None and (
                not isinstance(limit, dict)
                or set(limit) - {'context', 'output'}
                or any(not (type(limit[key]) is int
                            or (type(limit[key]) is float and math.isfinite(limit[key]))) for key in limit)
        ):
            raise CheckError('selected OpenCode model limit is noncanonical')
        variants = model_definition.get('variants')
        if variants is not None and (
                not isinstance(variants, dict)
                or any(not isinstance(variant, str) or not variant
                       or not isinstance(values, dict)
                       or set(values) != {'reasoningEffort'}
                       or not isinstance(values['reasoningEffort'], str)
                       or not values['reasoningEffort']
                       for variant, values in variants.items())
        ):
            raise CheckError('selected OpenCode model variants are noncanonical')
    elif 'provider' in runtime_config:
        raise CheckError('unexpected OpenCode provider definition')
    canonical(root, 'SKILL.md')
    if config is None:
        config = resolved(runtime, env, ['debug', 'config', '--pure'])
    if config.get('plugin_origins') or config.get('plugin') or config.get('mcp'):
        raise CheckError('external plugins or MCP clients are not allowed')
    if agent is None:
        agent = resolved(runtime, env, ['debug', 'agent', f'spec-reviewer-{depth}', '--pure'])
    tools = agent.get('tools', {})
    # Fail closed on a changed debug schema as well as on enabled unknown tools.
    if not isinstance(tools, dict) or not tools:
        raise CheckError('effective tool catalog unavailable')
    enabled = {name for name, value in tools.items() if value is True}
    if enabled != ALLOWED:
        raise CheckError(f'effective tool isolation mismatch: {sorted(enabled)}')
    permissions = agent.get('permission', [])
    if not isinstance(permissions, list) or not permissions:
        raise CheckError('effective permissions unavailable')
    for name in ALLOWED | {'bash', 'edit', 'task', 'webfetch', 'websearch', 'read', 'glob', 'grep', 'external_directory'}:
        matching = [p for p in permissions if p.get('permission') in ('*', name) and p.get('pattern') == '*']
        expected_action = 'allow' if name in ALLOWED else 'deny'
        if not matching or matching[-1].get('action') != expected_action:
            raise CheckError(f'effective permission mismatch: {name}')
    external = [p for p in permissions if p.get('permission') == 'external_directory']
    patterns = {p.get('pattern') for p in external}
    for pattern in patterns:
        matching = [p for p in permissions if p.get('permission') in ('*', 'external_directory')
                    and p.get('pattern') in ('*', pattern)]
        if matching[-1].get('action') != 'deny':
            raise CheckError('trailing external-directory allow')
    return {'ok': True, 'tools': sorted(enabled),
            'sha256': hashlib.sha256(expected[directory / 'tools/lean_review.ts']).hexdigest()}


def resolved(runtime: Path, env: dict, arguments: list[str]) -> dict:
    result = subprocess.run(['opencode', *arguments], cwd=runtime, env=env,
                            capture_output=True, text=True, timeout=180)
    if result.returncode:
        raise CheckError('OpenCode runtime preflight failed')
    try:
        value = json.loads(result.stdout)
    except ValueError as exc:
        raise CheckError('OpenCode preflight returned no JSON') from exc
    if not isinstance(value, dict):
        raise CheckError('unexpected OpenCode preflight schema')
    return value


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--skill-root', type=Path, required=True)
    parser.add_argument('--runtime', type=Path, required=True)
    parser.add_argument('--depth', choices=('lite', 'strict'), default='lite')
    args = parser.parse_args()
    try:
        print(json.dumps(check(args.skill_root, args.runtime, dict(os.environ), depth=args.depth)))
    except (CheckError, OSError, subprocess.SubprocessError) as exc:
        print(f'BLOCKED: {exc}')
        raise SystemExit(1)
